name: Scrape PHIVOLCS

on:
    schedule:
        - cron: '*/30 * * * *' # Every 30 minutes
    workflow_dispatch:
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                
            - name: Install dependencies
              run: |
                pip install -r requirements.txt
                python scrape_philvolcs.py

            - name: Commit updated CSV
              run: |
                git config user.name "GitHub Action"
                git config user.email "action@github.com"
                git add earthquakes.csv
                git commit -m "Update earthquake data" || echo "No changes to commit"
                git push
